# Generated by Django 3.0.4 on 2020-05-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('subtype', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small')], max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaladsPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubsPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small')], max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pizza', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza')),
            ],
        ),
    ]
