# Generated by Django 3.0.4 on 2020-05-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200519_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saladspasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subsplatters',
            name='price',
            field=models.FloatField(),
        ),
    ]
