# Generated by Django 3.0.4 on 2020-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200519_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('pizza', models.ManyToManyField(blank=True, related_name='customers', to='orders.Pizza')),
                ('salads_pasta', models.ManyToManyField(blank=True, related_name='customers', to='orders.SaladsPasta')),
                ('subs_platters', models.ManyToManyField(blank=True, related_name='customers', to='orders.SubsPlatters')),
            ],
        ),
    ]
