# Generated by Django 3.0.4 on 2020-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200520_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='total_price',
            field=models.FloatField(blank=True),
        ),
    ]
