# Generated by Django 3.0.4 on 2020-05-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200520_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
