# Generated by Django 3.0.4 on 2020-05-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200520_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSalads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.SaladsPasta')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.SubsPlatters')),
            ],
        ),
        migrations.CreateModel(
            name='FinalToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FinalPizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AddField(
            model_name='finalsubs',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Receipt'),
        ),
        migrations.AddField(
            model_name='finalsalads',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Receipt'),
        ),
        migrations.AddField(
            model_name='finalpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='finalpizza',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Receipt'),
        ),
    ]
