# Generated by Django 3.0.4 on 2020-05-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200521_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltoppings',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Toppings'),
        ),
    ]
