# Generated by Django 3.0.4 on 2020-05-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200521_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='finalpizza',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pizza', to='orders.Receipt'),
        ),
        migrations.AlterField(
            model_name='finalsalads',
            name='salads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SaladsPasta'),
        ),
        migrations.AlterField(
            model_name='finalsalads',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_salads', to='orders.Receipt'),
        ),
        migrations.AlterField(
            model_name='finalsubs',
            name='subs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubsPlatters'),
        ),
        migrations.AlterField(
            model_name='finalsubs',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_subs', to='orders.Receipt'),
        ),
        migrations.AlterField(
            model_name='finaltoppings',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_toppings', to='orders.FinalPizza'),
        ),
        migrations.AlterField(
            model_name='finaltoppings',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
    ]
